# Pre-commit configuration for Python project
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--line-length=180]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [-r]

minimum_pre_commit_version: "3.2.0"
default_language_version:
  python: python3.12

exclude: |
  (?x)^(
      \.venv/|
      __pycache__/|
      \.eggs/|
      \.git/|
      \.hg/|
      \.mypy_cache/|
      \.tox/|
      _build/|
      buck-out/|
      build/|
      dist/|
      node_modules/|
      \.vscode/|
      \.idea/
  )$
